# Generated by Django 5.0.4 on 2024-04-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='access_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='stored_password',
        ),
    ]
