# Generated by Django 5.0.4 on 2024-04-19 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_access_level_user_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegistration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=100)),
                ('client_type', models.CharField(max_length=20)),
                ('identifier', models.CharField(max_length=14)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_payment', models.DateField()),
                ('type_of_bill', models.CharField(max_length=100)),
                ('invoice', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(max_length=50)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientregistration')),
            ],
        ),
        migrations.CreateModel(
            name='EntryValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_action', models.CharField(max_length=100)),
                ('received_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clientregistration')),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
